# Generated by Django 4.2.7 on 2023-12-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applies', '0002_applycourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycourse',
            name='abroad_season',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applycourse',
            name='abroad_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applycourse',
            name='course_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applycourse',
            name='preferred_college',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliablecourses',
            name='country_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
