# Generated by Django 4.2.7 on 2023-12-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applies', '0005_alter_foreignlanguageapplied_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitiveCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('short_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
