# Generated by Django 4.2.7 on 2023-12-22 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applies', '0007_competitivecourseapplied'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitivecourseapplied',
            options={'permissions': [('view_gre_course', 'Can view Gre course'), ('view_gate_course', 'Can view Gate course'), ('view_upsc_course', 'Can view Upsc course'), ('view_ielts_course', 'Can view Ielts course')]},
        ),
        migrations.AlterModelOptions(
            name='foreignlanguageapplied',
            options={'permissions': [('view_german_lang', 'Can view german language'), ('view_french_lang', 'Can view french language'), ('view_japanese_lang', 'Can view japanese language'), ('view_spanish_lang', 'Can view spanish language')]},
        ),
        migrations.AddField(
            model_name='competitivecourseapplied',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competitivecourseapplied',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='foreignlanguageapplied',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foreignlanguageapplied',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
