# Generated by Django 4.2.7 on 2023-11-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_college',
            field=models.TextField(blank=True, null=True),
        ),
    ]
