# Generated by Django 4.2.7 on 2023-12-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_preferred_college'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('change_userpassword', 'Can Change User Password')]},
        ),
    ]
