# Generated by Django 4.2.7 on 2023-11-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_ignored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactus',
            name='is_replyed',
            field=models.BooleanField(default=False),
        ),
    ]
